export const NAV_ITEMS = [
  { label: "О компании", href: "/about" },
  { label: "КриптоМетры", href: "/cryptometry" },
  { label: "Внутренние службы", href: "/directions" },
  { label: "Roadmap", href: "/roadmap" },
  { label: "Глоссарий", href: "/glossary" },
  { label: "Контакты", href: "/contacts" },
];

export const DIRECTIONS = [
  {
    id: "cryptometry",
    icon: "Hexagon",
    title: "КриптоМетры",
    subtitle: "Flagship · Distributed Development",
    desc: "Флагманская система распределённого девелопмента и цифровой архитектуры участия в недвижимости. Объединяет землевладельцев, девелоперов и участников в единой среде.",
    color: "cyan",
    stat: "Флагман",
    tags: ["Распределённый девелопмент", "Цифровое участие", "Платформа"],
  },
  {
    id: "ai-lab",
    icon: "BrainCircuit",
    title: "Лаборатория ИИ",
    subtitle: "AI Lab · PropTech Intelligence",
    desc: "Разработка специализированных ИИ-решений для недвижимости, земельного рынка, девелопмента, аналитики, управления и цифровых интерфейсов.",
    color: "purple",
    stat: "AI R&D",
    tags: ["Земельный рынок", "Аналитика", "Цифровые интерфейсы"],
  },
  {
    id: "ai-production",
    icon: "Clapperboard",
    title: "ИИ-продакшн",
    subtitle: "AI Production · Digital Media",
    desc: "Создание ИИ-аватаров, корпоративных цифровых персонажей, видеопрезентаций, медийных оболочек и объясняющих визуальных коммуникаций для бизнеса.",
    color: "cyan",
    stat: "AI Media",
    tags: ["ИИ-аватары", "Видеопрезентации", "Digital Brand"],
  },
  {
    id: "invest-models",
    icon: "Network",
    title: "Коллективные инвестиционные модели",
    subtitle: "Collective Models · Structured Participation",
    desc: "Проектирование юридически корректных моделей коллективного участия в проектах недвижимости и инфраструктуры. Акцент — на структуре, логике и архитектуре, а не на привлечении средств.",
    color: "purple",
    stat: "Структуры",
    tags: ["Инвестиционная логика", "Юридические модели", "Архитектура участия"],
  },
  {
    id: "property-mgmt",
    icon: "Building2",
    title: "Управление недвижимостью",
    subtitle: "Property Management · Digital Ops",
    desc: "Цифровое и операционное управление объектами: эксплуатация, постдевелоперское сопровождение, сервисные и доходные процессы на базе цифровых инструментов.",
    color: "cyan",
    stat: "Операции",
    tags: ["Эксплуатация", "Постдевелопмент", "Доходные объекты"],
  },
  {
    id: "lss",
    icon: "Search",
    title: "Служба земельного поиска LSS",
    subtitle: "Land Search Service · Analytics",
    desc: "Аналитический поиск, фильтрация и предварительная структуризация земельных активов для девелопмента, инвестиций и редевелопмента.",
    color: "purple",
    stat: "LSS",
    tags: ["Поиск участков", "Фильтрация активов", "Редевелопмент"],
  },
  {
    id: "land-data",
    icon: "DatabaseZap",
    title: "Земельная аналитика & Data",
    subtitle: "Land Intelligence · Data Products",
    desc: "Базы данных, цифровые досье, картографические решения, аналитические панели и data-продукты для работы с земельными и девелоперскими активами.",
    color: "cyan",
    stat: "Data",
    tags: ["Базы данных", "Картография", "Аналитические панели"],
  },
  {
    id: "fee-dev",
    icon: "Settings2",
    title: "Девелоперский оператор",
    subtitle: "Fee-Development Platform · Operator",
    desc: "АО КСИ как оператор среды для профессиональных девелоперов: упаковка активов, структурирование проектов, логика реализации и интеграция исполнителей.",
    color: "purple",
    stat: "Fee-Dev",
    tags: ["Упаковка активов", "Структурирование", "Исполнители"],
  },
  {
    id: "licensing",
    icon: "PackageCheck",
    title: "Лицензирование технологий",
    subtitle: "Tech Licensing · Digital Solutions",
    desc: "Передача внешним партнёрам разработанных ИИ-сервисов, аналитических интерфейсов, медийных и цифровых решений по лицензионным моделям.",
    color: "cyan",
    stat: "Лицензии",
    tags: ["ИИ-сервисы", "White-label", "API & SaaS"],
  },
  {
    id: "media",
    icon: "Newspaper",
    title: "Медиа & Аналитический центр",
    subtitle: "Media Hub · Research & Insights",
    desc: "Публикации, исследования, рыночные обзоры, аналитические позиции и интеллектуальное сопровождение отрасли недвижимости и девелопмента.",
    color: "purple",
    stat: "Медиа",
    tags: ["Исследования", "Рыночная аналитика", "Контент"],
  },
  {
    id: "consulting",
    icon: "Compass",
    title: "Стратегический консалтинг",
    subtitle: "Advisory · Strategic Development",
    desc: "Экспертное сопровождение девелоперских и инвестиционных проектов: стратегия выхода на рынок, позиционирование активов, цифровая трансформация бизнеса.",
    color: "cyan",
    stat: "Advisory",
    tags: ["Стратегия", "Трансформация", "Экспертиза"],
  },
  {
    id: "edu",
    icon: "GraduationCap",
    title: "Образовательная платформа",
    subtitle: "Education · PropTech Academy",
    desc: "Программы, курсы и профессиональная среда для участников рынка недвижимости: от введения в цифровой девелопмент до продвинутых ИИ-инструментов.",
    color: "purple",
    stat: "Обучение",
    tags: ["Курсы", "Профессиональная среда", "PropTech Academy"],
  },
];

export const PROJECTS = [
  {
    tag: "ФЛАГМАН",
    icon: "Hexagon",
    name: "КриптоМетры",
    type: "Система распределённого девелопмента",
    desc: "Флагманская платформа АО КСИ. Цифровая архитектура участия в недвижимости: объединяет землевладельцев, девелоперов и профессиональных участников в единой управляемой среде с прозрачной логикой проектов.",
    features: [
      { icon: "GitBranch", text: "Распределённая модель девелопмента" },
      { icon: "Users", text: "Многостороннее участие: земля, капитал, экспертиза" },
      { icon: "BrainCircuit", text: "ИИ-аналитика и поддержка решений" },
      { icon: "ShieldCheck", text: "Прозрачная структура проекта" },
      { icon: "FileText", text: "Цифровое сопровождение сделки" },
    ],
    status: "Активна",
    color: "cyan",
  },
  {
    tag: "ИИ-СЕРВИС",
    icon: "BrainCircuit",
    name: "Лаборатория ИИ",
    type: "Специализированные ИИ-решения для рынка",
    desc: "R&D-подразделение экосистемы. Разрабатывает и внедряет ИИ-инструменты для земельного рынка, девелопмента, аналитики активов, управления объектами и цифровых интерфейсов взаимодействия.",
    features: [
      { icon: "Map", text: "ИИ-анализ земельных активов" },
      { icon: "BarChart2", text: "Аналитические модели и прогнозирование" },
      { icon: "Cpu", text: "Агенты автоматизации due diligence" },
      { icon: "Layers", text: "Цифровые интерфейсы управления" },
      { icon: "PackageCheck", text: "Лицензирование ИИ-решений партнёрам" },
    ],
    status: "R&D",
    color: "purple",
  },
  {
    tag: "DATA-СЕРВИС",
    icon: "Search",
    name: "Служба земельного поиска LSS",
    type: "Land Search Service · Аналитика активов",
    desc: "Сервис аналитического поиска, фильтрации и предварительной структуризации земельных активов. Работает с объектами под девелопмент, инвестиции и редевелопмент по всей России.",
    features: [
      { icon: "ScanSearch", text: "Многопараметрическая фильтрация участков" },
      { icon: "DatabaseZap", text: "Цифровые досье и земельная аналитика" },
      { icon: "MapPin", text: "Картографические решения и тепловые карты" },
      { icon: "ClipboardList", text: "Предварительная структуризация активов" },
      { icon: "RefreshCw", text: "Редевелопмент и репозиционирование" },
    ],
    status: "Beta",
    color: "cyan",
  },
  {
    tag: "МЕДИА",
    icon: "Clapperboard",
    name: "ИИ-продакшн",
    type: "Digital Media · AI Avatars & Content",
    desc: "Создание корпоративных цифровых персонажей, ИИ-аватаров, видеопрезентаций и объясняющих интерфейсов. Медийная оболочка для девелоперских проектов, брендов и цифровых продуктов.",
    features: [
      { icon: "Bot", text: "ИИ-аватары и цифровые персонажи" },
      { icon: "Video", text: "Видеопрезентации и объясняющий контент" },
      { icon: "Sparkles", text: "Визуальные коммуникации бренда" },
      { icon: "Monitor", text: "Объясняющие интерфейсы и UX-нарративы" },
      { icon: "Globe", text: "Медийная оболочка для проектов" },
    ],
    status: "Активна",
    color: "purple",
  },
  {
    tag: "ОПЕРАТОР",
    icon: "Settings2",
    name: "Fee-Dev Платформа",
    type: "Девелоперский оператор · Среда для профи",
    desc: "АО КСИ как оператор профессиональной девелоперской среды. Упаковка активов, структурирование проектов, интеграция подрядчиков и экспертов, логика реализации под ключ.",
    features: [
      { icon: "Package", text: "Упаковка и позиционирование активов" },
      { icon: "Network", text: "Подключение профессиональных исполнителей" },
      { icon: "Workflow", text: "Структурирование логики реализации" },
      { icon: "FileCheck", text: "Сопровождение сделок и документации" },
      { icon: "TrendingUp", text: "Контроль экономики проекта" },
    ],
    status: "Активна",
    color: "cyan",
  },
];

export const STATS = [
  { value: "₽2.4", suffix: " млрд", label: "Объём сделок под управлением" },
  { value: "150+", suffix: "", label: "Регионов в базе аналитики" },
  { value: "40+", suffix: "", label: "Партнёров экосистемы" },
  { value: "3", suffix: " платформы", label: "Цифровых продукта в экосистеме" },
];

export const ECOSYSTEM_NODES = [
  { id: "ksi", label: "АО КСИ", x: 50, y: 50, size: 60, color: "#00d4ff", isPrimary: true },
  { id: "km", label: "КриптоМетры", x: 50, y: 16, size: 44, color: "#00d4ff", isPrimary: false },
  { id: "analytics", label: "KSI Analytics", x: 79, y: 34, size: 36, color: "#7b2fff", isPrimary: false },
  { id: "devhub", label: "DevHub", x: 79, y: 66, size: 36, color: "#7b2fff", isPrimary: false },
  { id: "ai", label: "AI Engine", x: 50, y: 84, size: 32, color: "#00d4ff", isPrimary: false },
  { id: "blockchain", label: "Blockchain", x: 21, y: 66, size: 32, color: "#7b2fff", isPrimary: false },
  { id: "production", label: "Production", x: 21, y: 34, size: 32, color: "#00aaff", isPrimary: false },
];

export const CONNECTIONS = [
  ["ksi", "km"], ["ksi", "analytics"], ["ksi", "devhub"],
  ["ksi", "ai"], ["ksi", "blockchain"], ["ksi", "production"],
  ["km", "analytics"], ["km", "blockchain"], ["analytics", "ai"],
  ["devhub", "ai"], ["blockchain", "production"],
];